# Generated by Django 3.2.6 on 2021-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('director', models.TextField(null=True)),
                ('genre', models.CharField(max_length=500, null=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('imdb_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('released', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('imdb_no_votes', models.CharField(max_length=255, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
