# Generated by Django 2.2.1 on 2021-09-03 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210902_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='cast_members',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cast',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cast',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='display_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(null=True)),
                ('reviewed_by', models.CharField(max_length=255, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movie')),
            ],
        ),
    ]
